#!/bin/bash

usage (){
	echo ""
	echo "Usage: integrate_peaks ROOT_FILE [OUT_FILE]"
	echo "Compute the integrals and leading edge times of waveforms"
	echo "in an fADC125 root file. Supply an output file name as"
	echo "OUT_FILE to print results to a file instead of standard out."
	echo ""
}

if [ "$#" -lt 1 ] ; then usage ; exit ; fi

if [ "$#" -eq 1 ] ; then
	if [ ! -e "$1" ] ; then
		echo "file $1 does not exist!"
		exit
	fi
	exec 2> /dev/null
	echo "Wave Integral, Wave Leading Edge"
	cd macros
	root -q -b 'integrateMacro.c("../'"$1"'")' | grep '^[0-9]*,[0-9]*'
	cd ..
else
	if [ ! -e "$1" ] ; then
		echo "file $1 does not exist!"
		exit
	fi
	exec 2> /dev/null
	echo "Wave Integral, Wave Leading Edge" > "$2"
	cd macros
	root -q -b 'integrateMacro.c("../'"$1"'")' | grep '^[0-9]*,[0-9]*' >> ../"$2"
	cd ..
fi
